config/routes.rb
# frozen_string_literal: true

require 'admin_constraint'

Masha::Application.routes.draw do
  default_url_options ApplicationConfig.default_url_options.symbolize_keys
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if defined? LetterOpenerWeb
  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'welcome#index'

  get 'auth/:provider/callback', to: 'omniauth_session#create'
  post 'auth/:provider/callback', to: 'omniauth_session#create'
  # TODO: Добавить routes для отработки
  # http://masha.brandymint.ru/auth/failure?message=invalid_credentials&strategy=github

  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'login' => 'sessions#new', :as => 'login'
  get 'signup' => 'users#new', :as => 'signup'
  get 'feedback' => 'pages#feedback', :as => 'feedback'
  get 'noaccess' => 'pages#noaccess', :as => 'noaccess'
  get 'support' => redirect('/feedback')

  # Help routes
  get 'help', to: 'help#index', as: :help_index
  get 'help/guide', to: 'help#guide', as: :help_guide
  get 'help/quick-start', to: 'help#quick_start', as: :help_quick_start
  get 'help/commands', to: 'help#commands', as: :help_commands
  get 'help/time-format', to: 'help#time_format', as: :help_time_format
  get 'help/projects', to: 'help#projects', as: :help_projects
  get 'help/faq', to: 'help#faq', as: :help_faq
  get 'error' => 'errors#index', :as => 'error'

  resources :users, only: %i[new create]
  resources :sessions, only: %i[new create destroy]

  get 'ta/:id', action: :create, controller: 'telegram/attach', as: :attach_telegram

  get 'telegram/auth_callback', to: 'telegram_auth_callback#create'
  get 'telegram/confirm', to: 'telegram_auth_callback#confirm'
  if Rails.env.test?
    # В тестовой среде определяем роуты вручную для integration тестов
    post '/telegram/:token', to: 'telegram/webhook#create', defaults: { format: :json }
  else
    telegram_webhook Telegram::WebhookController
  end

  constraints subdomain: 'admin' do
    constraints AdminConstraint do
      mount SolidQueueDashboard::Engine, at: '/solid-queue'
    end
  end

  # Личный контроллер пользователя
  resource :profile, controller: :profile do
    collection do
      post :change_password
    end
  end

  resources :password_resets, only: %i[new create edit update]

  resources :projects do
    resources :memberships
    member do
      put :activate
      put :archivate
    end
  end
  resources :time_shifts do
    collection do
      get :summary
    end
  end
  resources :invites, only: %i[create destroy]

  namespace :owner do
    root controller: :users, action: :index
    resources :projects do
      resources :memberships

      member do
        post :set_role
        delete :remove_role
      end
    end
    resources :users
  end

  resources :users
end

app/controllers/help_controller.rb
# frozen_string_literal: true

class HelpController < ApplicationController
  skip_before_action :require_login, raise: false

  def index; end

  def guide; end

  def quick_start; end

  def commands; end

  def time_format; end

  def projects; end

  def faq; end
end

app/views/help/_nav.html.haml
.help-navigation
  %nav.navbar.navbar-expand-sm.navbar-light.bg-light
    .container
      %button.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarNav", "data-bs-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      #navbarNav.collapse.navbar-collapse
        %ul.navbar-nav.ms-auto
          %li.nav-item
            = link_to t('help.nav.index'), help_index_path, class: 'nav-link'
          %li.nav-item
            = link_to t('help.nav.quick_start'), help_quick_start_path, class: 'nav-link'
          %li.nav-item
            = link_to t('help.nav.guide'), help_guide_path, class: 'nav-link'
          %li.nav-item
            = link_to t('help.nav.commands'), help_commands_path, class: 'nav-link'
          %li.nav-item
            = link_to t('help.nav.time_format'), help_time_format_path, class: 'nav-link'
          %li.nav-item
            = link_to t('help.nav.projects'), help_projects_path, class: 'nav-link'
          %li.nav-item
            = link_to t('help.nav.faq'), help_faq_path, class: 'nav-link'

app/views/help/commands.html.haml
= render 'nav'

.container.mt-4
  .row
    .col-md-9
      %h1= t('help.commands.title')

      %h2= t('help.commands.basic')

      .command.mb-4
        %h3
          %code /start
        %p= t('help.commands.start_desc')

      .command.mb-4
        %h3
          %code /add
        %p= t('help.commands.add_desc')

      .command.mb-4
        %h3
          %code /report
        %p= t('help.commands.report_desc')

      .command.mb-4
        %h3
          %code /projects
        %p= t('help.commands.projects_desc')

      .command.mb-4
        %h3
          %code /clients
        %p= t('help.commands.clients_desc')

      %h2= t('help.commands.admin')

      .command.mb-4
        %h3
          %code /notify
        %p= t('help.commands.notify_desc')

      .alert.alert-info.mt-4
        %strong= t('help.commands.more_info')
        = link_to t('help.nav.time_format'), help_time_format_path

app/views/help/faq.html.haml
= render 'nav'

.container.mt-4
  .row
    .col-md-9
      %h1= t('help.faq.title')

      .accordion
        .accordion-item
          %h2.accordion-header
            %button.accordion-button{"aria-controls" => "faq1", "aria-expanded" => "true", "data-bs-target" => "#faq1", "data-bs-toggle" => "collapse", :type => "button"}
              = t('help.faq.q1')
          #faq1.accordion-collapse.collapse.show{"aria-labelledby" => "headingOne", "data-bs-parent" => ".accordion"}
            .accordion-body
              = t('help.faq.a1')

        .accordion-item
          %h2.accordion-header
            %button.accordion-button.collapsed{"aria-controls" => "faq2", "aria-expanded" => "false", "data-bs-target" => "#faq2", "data-bs-toggle" => "collapse", :type => "button"}
              = t('help.faq.q2')
          #faq2.accordion-collapse.collapse{"aria-labelledby" => "headingTwo", "data-bs-parent" => ".accordion"}
            .accordion-body
              = t('help.faq.a2')

        .accordion-item
          %h2.accordion-header
            %button.accordion-button.collapsed{"aria-controls" => "faq3", "aria-expanded" => "false", "data-bs-target" => "#faq3", "data-bs-toggle" => "collapse", :type => "button"}
              = t('help.faq.q3')
          #faq3.accordion-collapse.collapse{"aria-labelledby" => "headingThree", "data-bs-parent" => ".accordion"}
            .accordion-body
              = t('help.faq.a3')

        .accordion-item
          %h2.accordion-header
            %button.accordion-button.collapsed{"aria-controls" => "faq4", "aria-expanded" => "false", "data-bs-target" => "#faq4", "data-bs-toggle" => "collapse", :type => "button"}
              = t('help.faq.q4')
          #faq4.accordion-collapse.collapse{"aria-labelledby" => "headingFour", "data-bs-parent" => ".accordion"}
            .accordion-body
              = t('help.faq.a4')

        .accordion-item
          %h2.accordion-header
            %button.accordion-button.collapsed{"aria-controls" => "faq5", "aria-expanded" => "false", "data-bs-target" => "#faq5", "data-bs-toggle" => "collapse", :type => "button"}
              = t('help.faq.q5')
          #faq5.accordion-collapse.collapse{"aria-labelledby" => "headingFive", "data-bs-parent" => ".accordion"}
            .accordion-body
              = t('help.faq.a5')

app/views/help/guide.html.haml
= render 'nav'

.container.mt-4
  .row
    .col-md-9
      %h1= t('help.guide.title')

      %p.lead= t('help.guide.subtitle')

      .toc.mb-4.p-3.bg-light.rounded
        %h3= t('help.guide.table_of_contents')
        %ul
          %li= link_to t('help.guide.concepts'), '#concepts'
          %li= link_to t('help.guide.getting_started'), '#getting-started'
          %li= link_to t('help.guide.tracking_time'), '#tracking-time'
          %li= link_to t('help.guide.reports'), '#reports'
          %li= link_to t('help.guide.projects'), '#projects'

      %h2#concepts= t('help.guide.concepts')

      %h3= t('help.guide.project')
      %p= t('help.guide.project_desc')

      %h3= t('help.guide.time_entry')
      %p= t('help.guide.time_entry_desc')

      %h3= t('help.guide.roles')
      %p= t('help.guide.roles_desc')
      %ul
        %li
          %strong Owner:
          = t('help.guide.role_owner')
        %li
          %strong Watcher:
          = t('help.guide.role_watcher')
        %li
          %strong Participant:
          = t('help.guide.role_participant')

      %h2#getting-started= t('help.guide.getting_started')
      %p
        = t('help.guide.getting_started_desc')
        = link_to t('help.nav.quick_start'), help_quick_start_path

      %h2#tracking-time= t('help.guide.tracking_time')
      %p
        = t('help.guide.tracking_time_desc')
        = link_to t('help.nav.time_format'), help_time_format_path

      %h2#reports= t('help.guide.reports')
      %p= t('help.guide.reports_desc')
      %p
        %code.d-block.mb-2 /report week
        %code.d-block.mb-2 /report month
        %code.d-block.mb-2 /report today

      %h2#projects= t('help.guide.projects')
      %p
        = t('help.guide.projects_desc')
        = link_to t('help.nav.projects'), help_projects_path

app/views/help/index.html.haml
= render 'nav'

.container.mt-4
  .row
    .col-md-8
      %h1= t('help.index.title')

      %p.lead= t('help.index.intro')

      %h2= t('help.index.getting_started')
      %ol
        %li
          %strong= t('help.index.step1_title')
          %p= t('help.index.step1_desc')
        %li
          %strong= t('help.index.step2_title')
          %p= t('help.index.step2_desc')
        %li
          %strong= t('help.index.step3_title')
          %p= t('help.index.step3_desc')

      %h2= t('help.index.topics')
      .list-group
        = link_to t('help.nav.quick_start'), help_quick_start_path, class: 'list-group-item list-group-item-action'
        = link_to t('help.nav.guide'), help_guide_path, class: 'list-group-item list-group-item-action'
        = link_to t('help.nav.commands'), help_commands_path, class: 'list-group-item list-group-item-action'
        = link_to t('help.nav.time_format'), help_time_format_path, class: 'list-group-item list-group-item-action'
        = link_to t('help.nav.projects'), help_projects_path, class: 'list-group-item list-group-item-action'
        = link_to t('help.nav.faq'), help_faq_path, class: 'list-group-item list-group-item-action'

    .col-md-4
      %aside.help-sidebar
        .card
          .card-header
            %h5 💡 = t('help.sidebar.tip')
          .card-body
            %p= t('help.sidebar.quick_commands')
            %div
              %code.d-block.mb-2= '/start'
              %code.d-block.mb-2= '/projects'
              %code.d-block.mb-2= '/add'
              %code.d-block.mb-2= '/report'

app/views/help/projects.html.haml
= render 'nav'

.container.mt-4
  .row
    .col-md-9
      %h1= t('help.projects.title')

      %h2= t('help.projects.create')
      %p= t('help.projects.create_desc')

      .code-example.mb-4
        %pre.bg-light.p-3
          %code /projects create my-project

      %h2= t('help.projects.view')
      %p= t('help.projects.view_desc')

      .code-example.mb-4
        %pre.bg-light.p-3
          %code /projects

      %h2= t('help.projects.show')
      %p= t('help.projects.show_desc')

      .code-example.mb-4
        %pre.bg-light.p-3
          %code /projects show my-project

      %h2= t('help.projects.edit')
      %p= t('help.projects.edit_desc')

      .code-example.mb-4
        %pre.bg-light.p-3
          %code /projects edit my-project

      %h2= t('help.projects.delete')
      %p= t('help.projects.delete_desc')

      .code-example.mb-4
        %pre.bg-light.p-3
          %code /projects delete my-project

      .alert.alert-warning.mt-4
        %strong= t('help.projects.warning')
        %p.mb-0= t('help.projects.warning_desc')

app/views/help/quick_start.html.haml
= render 'nav'

.container.mt-4
  .row
    .col-md-9
      %h1= t('help.quick_start.title')

      %p.lead= t('help.quick_start.subtitle')

      %h2#what-is-masha= t('help.quick_start.what_is')
      %p= t('help.quick_start.what_is_desc')

      %h2#three-steps= t('help.quick_start.three_steps')

      .step.mb-4
        %h3
          %span.badge.bg-primary 1
          = t('help.quick_start.step1_title')
        %p= t('help.quick_start.step1_desc')
        %pre.bg-light.p-3
          %code /projects create my-project

      .step.mb-4
        %h3
          %span.badge.bg-primary 2
          = t('help.quick_start.step2_title')
        %p= t('help.quick_start.step2_desc')
        %pre.bg-light.p-3
          %code 2 my-project Первая задача

      .step.mb-4
        %h3
          %span.badge.bg-primary 3
          = t('help.quick_start.step3_title')
        %p= t('help.quick_start.step3_desc')
        %pre.bg-light.p-3
          %code /report week

      %h2#common-mistakes= t('help.quick_start.common_mistakes')
      .alert.alert-warning
        %strong= t('help.quick_start.mistake1_title')
        %p.mb-0= t('help.quick_start.mistake1_desc')

      %h2#next-steps= t('help.quick_start.next_steps')
      %ul
        %li= link_to t('help.nav.guide'), help_guide_path
        %li= link_to t('help.nav.commands'), help_commands_path
        %li= link_to t('help.nav.faq'), help_faq_path

app/views/help/time_format.html.haml
= render 'nav'

.container.mt-4
  .row
    .col-md-9
      %h1= t('help.time_format.title')

      %h2= t('help.time_format.basic_format')
      %p= t('help.time_format.basic_format_desc')

      .code-example.mb-4
        %pre.bg-light.p-3
          %code
            2 my-project Работа над задачей
        %p.small.text-muted
          = t('help.time_format.basic_example')

      %h2= t('help.time_format.decimal_hours')
      %p= t('help.time_format.decimal_hours_desc')

      .code-example.mb-4
        %pre.bg-light.p-3
          %code
            1.5 design Правка дизайна
        %p.small.text-muted
          = t('help.time_format.decimal_example')

      %h2= t('help.time_format.time_first')
      %p= t('help.time_format.time_first_desc')

      .code-example.mb-4
        %pre.bg-light.p-3
          %code
            /add 2 my-project Описание
        %p.small.text-muted
          = t('help.time_format.time_first_example')

      %h2= t('help.time_format.validation')
      %p= t('help.time_format.validation_desc')
      %ul
        %li= t('help.time_format.min_hours')
        %li= t('help.time_format.max_description')
        %li= t('help.time_format.project_required')