config/routes.rb
# frozen_string_literal: true

require 'admin_constraint'

Masha::Application.routes.draw do
  default_url_options ApplicationConfig.default_url_options.symbolize_keys
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if defined? LetterOpenerWeb
  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'welcome#index'

  get 'auth/:provider/callback', to: 'omniauth_session#create'
  post 'auth/:provider/callback', to: 'omniauth_session#create'
  # TODO: Добавить routes для отработки
  # http://masha.brandymint.ru/auth/failure?message=invalid_credentials&strategy=github

  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'login' => 'sessions#new', :as => 'login'
  get 'signup' => 'users#new', :as => 'signup'
  get 'feedback' => 'pages#feedback', :as => 'feedback'
  get 'noaccess' => 'pages#noaccess', :as => 'noaccess'
  get 'support' => redirect('/feedback')

  # Help routes
  get 'help', to: 'help#index', as: :help_index
  get 'help/guide', to: 'help#guide', as: :help_guide
  get 'help/quick-start', to: 'help#quick_start', as: :help_quick_start
  get 'help/commands', to: 'help#commands', as: :help_commands
  get 'help/time-format', to: 'help#time_format', as: :help_time_format
  get 'help/projects', to: 'help#projects', as: :help_projects
  get 'help/faq', to: 'help#faq', as: :help_faq
  get 'error' => 'errors#index', :as => 'error'

  resources :users, only: %i[new create]
  resources :sessions, only: %i[new create destroy]

  get 'ta/:id', action: :create, controller: 'telegram/attach', as: :attach_telegram

  get 'telegram/auth_callback', to: 'telegram_auth_callback#create'
  get 'telegram/confirm', to: 'telegram_auth_callback#confirm'
  if Rails.env.test?
    # В тестовой среде определяем роуты вручную для integration тестов
    post '/telegram/:token', to: 'telegram/webhook#create', defaults: { format: :json }
  else
    telegram_webhook Telegram::WebhookController
  end

  constraints subdomain: 'admin' do
    constraints AdminConstraint do
      mount SolidQueueDashboard::Engine, at: '/solid-queue'
    end
  end

  # Личный контроллер пользователя
  resource :profile, controller: :profile do
    collection do
      post :change_password
    end
  end

  resources :password_resets, only: %i[new create edit update]

  resources :projects do
    resources :memberships
    member do
      put :activate
      put :archivate
    end
  end
  resources :time_shifts do
    collection do
      get :summary
    end
  end
  resources :invites, only: %i[create destroy]

  namespace :owner do
    root controller: :users, action: :index
    resources :projects do
      resources :memberships

      member do
        post :set_role
        delete :remove_role
      end
    end
    resources :users
  end

  resources :users
end

app/models/membership.rb
# frozen_string_literal: true

# Связь пользователя с проектом через роль (owner/viewer/member). Обеспечивает систему прав доступа.
# Отправляет уведомления при добавлении участника.
class Membership < ApplicationRecord
  include Authority::Abilities

  belongs_to :user
  belongs_to :project

  has_many :available_users, through: :project, source: :users
  has_many :authentications, through: :user

  after_initialize :set_defaults
  after_commit :notify_project_members, on: :create

  self.authorizer_name = 'MembershipAuthorizer'

  scope :last_updates,    -> { order('updated_at desc') }
  scope :viewable,        -> { order 'role_cd < 2' }
  scope :ordered_by_role, -> { order :role_cd }
  scope :owners,          -> { where role_cd: 0 }
  scope :viewers,         -> { where role_cd: 1 }
  scope :members,         -> { where role_cd: 2 }
  scope :supervisors,     -> { where 'role_cd = 0 or role_cd = 1' }
  scope :subscribers,     -> { includes(:user).where users: { subscribed: true } }

  as_enum :role, owner: 0, viewer: 1, member: 2
  DEFAULT_ROLE = :member

  validates :user_id, uniqueness: { scope: :project_id }

  def set_defaults
    self.role ||= DEFAULT_ROLE # will set the default value only if it's nil
  end

  private

  def notify_project_members
    ProjectMemberNotificationJob.perform_later(
      project_id: project.id,
      new_member_id: user.id
    )
  end
end

app/controllers/memberships_controller.rb
# frozen_string_literal: true

class MembershipsController < ApplicationController
  before_action :require_login

  helper_method :users_available_for_project

  inherit_resources
  belongs_to :project

  def index
    @invite = Invite.new

    super
  end

  def show
    redirect_to project_memberships_url(@project)
  end

  def create
    @project = parent

    @membership = Membership.new project: @project, user: current_user
    authorize_action_for @membership

    if invite_params[:user_id]
      @invite = Invite.new
      user = User.find invite_params[:user_id]
      @project.memberships.create user: user, role: invite_params[:role]
      render(:index)
    else

      user = find_user invite_params[:email]

      if user.present?
        @project.memberships.create user: user, role: invite_params[:role]
      else
        is = InviteService.new @project, invite_params
        is.make_invite(
          success: -> { flash.now[:success] = (t 'flash.invite_sent', email: is.invite.email) },
          failure: lambda {
            flash.now[:error] = (t 'flash.invite_error', email: is.invite.email
                                 render(:index) and return)
          }
        )

        @invite = is.invite
      end
      redirect_to project_memberships_url(@project)
    end
  end

  def update
    @membership = Membership.find params[:id]
    authorize_action_for(@membership)
    @membership.role = membership_params[:role]
    @membership.save!

    redirect_to project_memberships_url(parent)
  end

  def destroy
    @membership = Membership.find params[:id]
    authorize_action_for(@membership)
    @membership.destroy

    redirect_to project_memberships_url(parent)
  end

  protected

  def find_user(email)
    if /@/=~ email
      User.where(email: email).first
    else
      User.where(nickname: email).first || User.where(name: email).first
    end
  end

  def users_available_for_project
    @users_available_for_project ||= current_user.available_users.to_a - parent.users
  end

  def membership_params
    params.expect(membership: [:role])
  end

  def invite_params
    params.expect(invite: %i[email role user_id]).merge(user: current_user)
  end
end

app/controllers/owner/memberships_controller.rb
# frozen_string_literal: true

module Owner
  class MembershipsController < Owner::BaseController
    inherit_resources
    belongs_to :project
  end
end

app/views/memberships/_form.html.haml
%h3 Пригласить пользователя
%hr
= simple_form_for @invite, :url => project_memberships_url(@project), :method => :post, html: {class: 'form-inline-controls form-inline'} do |f|
  = f.error_notification
  .form-inputs
    = f.input :email, :require => true, label: false
    = f.input :role, :collection => roles_collection, :include_blank => false, :selected => Membership::DEFAULT_ROLE, label: false
    = f.button :submit, :class => 'btn btn-primary'

app/views/memberships/_membership.html.haml
- m = membership.decorate
%tr
  %td.col-xs-5
    = m.name
  %td.col-xs-5
    = roles_select m
  %td.col-xs-2
    = m.remove_link

app/views/memberships/_roles.html.haml
= simple_form_for m, :url => project_membership_path(m.project, m), :method => :patch do |f|
  = f.error_notification
  = f.input :role, :input_html => {:role => :submit_on_change}, :collection => roles_collection, :include_blank => false, :label => false, :selected => m.role

app/views/memberships/index.html.haml
= projects_link
%h1
  Проект '#{@project.slug}'
%div.m-t-md
  = edit_project_link @project if @project.active?
  = change_project_status_link @project
  = link_to 'Внести запись', new_time_shift_url(time_shift: { project_id: @project.id}), class: 'btn btn-default' if @project.active?
  = link_to 'Отчеты', time_shifts_url(time_sheet_form: { project_id: @project.id}), class: 'btn'
- 
%br
- unless @project.active?
  .label.label-default Проект в архиве
%h3 Участники
%table.table
  - @project.memberships.each do |m|
    - d = MembershipDecorator.decorate m
    %tr
      %td.col-xs-1
        = d.avatar
      %td.col-xs-4
        = d.name_as_link
      %td.col-xs-1
        = d.telegram_link
      %td.col-xs-4.form-inline-controls
        = roles_select m
      %td.col-xs-2
        = d.remove_link
%br
- if @project.active and current_user.can_create?(Membership.new(project: @project))
  = render 'form'
%br
- if @project.active and users_available_for_project.present?
  %h3 Возможно вы захотите их тоже пригласить
  %table.table
    - users_available_for_project.each do |u|
      - u = UserDecorator.new u
      - target_id = "invite_user-#{u.id}"
      %tr
        %td.col-xs-3
          = u.name
        %td.col-xs-9.form-inline-controls
          = select_tag :role, options_for_select(roles_collection, :include_blank => false, :selected => Membership::DEFAULT_ROLE), data: { target_id: "##{target_id}" }, role: 'membership_role_selector'
          %span.m-l-md= link_to 'Добавить', project_memberships_url( @project, invite: {user_id: u.id} ), method: :post, id: target_id, class: 'btn btn-primary btn-mini'
%hr
- if @project.invites.present?
  %h3 Приглашенные, но не принявшие
  %table.table
    - @project.invites.each do |i|
      - d = InviteDecorator.decorate i
      %tr
        %td.col-xs-5
          = i.email
        %td.col-xs-5
          = role_human i.role
        %td.col-xs-2
          = d.remove_link

%br
.panel.panel-default
  .panel-heading Роли участников проекта:
  .panel-body
    %ul.text-muted
      %li <em>Владалец</em> - имеет право добавлять/удалять и изменять роли участников проекта. Получает отчеты по всем участникам, может изменить любую информацию.
      %li <em>Смотритель</em> - имеет право только получать любые отчеты по всем участникам проекта.
      %li <em>Участник</em> - имеет право отмечать и изменять свое время. Не видит отчеты по другим участникам.