config/routes.rb
# frozen_string_literal: true

require 'admin_constraint'

Masha::Application.routes.draw do
  default_url_options ApplicationConfig.default_url_options.symbolize_keys
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if defined? LetterOpenerWeb
  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'welcome#index'

  get 'auth/:provider/callback', to: 'omniauth_session#create'
  post 'auth/:provider/callback', to: 'omniauth_session#create'
  # TODO: Добавить routes для отработки
  # http://masha.brandymint.ru/auth/failure?message=invalid_credentials&strategy=github

  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'login' => 'sessions#new', :as => 'login'
  get 'signup' => 'users#new', :as => 'signup'
  get 'feedback' => 'pages#feedback', :as => 'feedback'
  get 'noaccess' => 'pages#noaccess', :as => 'noaccess'
  get 'support' => redirect('/feedback')

  # Help routes
  get 'help', to: 'help#index', as: :help_index
  get 'help/guide', to: 'help#guide', as: :help_guide
  get 'help/quick-start', to: 'help#quick_start', as: :help_quick_start
  get 'help/commands', to: 'help#commands', as: :help_commands
  get 'help/time-format', to: 'help#time_format', as: :help_time_format
  get 'help/projects', to: 'help#projects', as: :help_projects
  get 'help/faq', to: 'help#faq', as: :help_faq
  get 'error' => 'errors#index', :as => 'error'

  resources :users, only: %i[new create]
  resources :sessions, only: %i[new create destroy]

  get 'ta/:id', action: :create, controller: 'telegram/attach', as: :attach_telegram

  get 'telegram/auth_callback', to: 'telegram_auth_callback#create'
  get 'telegram/confirm', to: 'telegram_auth_callback#confirm'
  if Rails.env.test?
    # В тестовой среде определяем роуты вручную для integration тестов
    post '/telegram/:token', to: 'telegram/webhook#create', defaults: { format: :json }
  else
    telegram_webhook Telegram::WebhookController
  end

  constraints subdomain: 'admin' do
    constraints AdminConstraint do
      mount SolidQueueDashboard::Engine, at: '/solid-queue'
    end
  end

  # Личный контроллер пользователя
  resource :profile, controller: :profile do
    collection do
      post :change_password
    end
  end

  resources :password_resets, only: %i[new create edit update]

  resources :projects do
    resources :memberships
    member do
      put :activate
      put :archivate
    end
  end
  resources :time_shifts do
    collection do
      get :summary
    end
  end
  resources :invites, only: %i[create destroy]

  namespace :owner do
    root controller: :users, action: :index
    resources :projects do
      resources :memberships

      member do
        post :set_role
        delete :remove_role
      end
    end
    resources :users
  end

  resources :users
end

app/models/time_shift.rb
# frozen_string_literal: true

# Запись о затраченном времени на проект. Содержит дату, количество часов,
# привязку к проекту и пользователю. Отправляет уведомления при создании.
class TimeShift < ApplicationRecord
  include Authority::Abilities

  self.authorizer_name = 'TimeShiftAuthorizer'

  scope :ordered, -> { order 'date desc, created_at desc' }
  scope :this_day, -> { where ['created_at >= ?', Time.zone.today - 24.hours] }

  belongs_to :project
  belongs_to :user

  validates :project, presence: true
  validates :user, presence: true
  validates :date, timeliness: { on_or_before: -> { Time.zone.today }, type: :date }
  validates :hours, presence: true, numericality: { greater_than_or_equal_to: 0.1 }

  after_commit on: :create do
    ViewerMailer.new_time_shift_email(self).deliver_later
  end
end

app/controllers/time_shifts_controller.rb
# frozen_string_literal: true

class TimeShiftsController < ApplicationController
  before_action :require_login
  inherit_resources

  def summary
    @time_sheet_form = TimeSheetForm.build_from_params params[:time_sheet_form]

    template = 'summary'

    respond_to do |format|
      format.xlsx { render xlsx: template }
      format.csv  { send_data build_summary.to_csv }
      format.html { render action: template, locals: { result: build_summary } }
    end
  end

  def index
    if viewable_projects_collection.empty?
      render 'no_projects'
    else
      @time_sheet_form = TimeSheetForm.build_from_params params[:time_sheet_form]
      return render 'blank', locals: { result: build_summary } if params[:time_sheet_form].blank?
      return render 'empty' unless @time_sheet_form.valid?

      template = 'index'
      query = TimeSheetQuery.new @time_sheet_form

      query.available_projects = current_user.available_projects
      query.available_users = current_user.available_users
      query.perform

      respond_to do |format|
        format.xlsx { render xlsx: template, locals: { result: query } }
        format.csv  { send_data query.to_csv }
        format.html { render action: template, locals: { result: query } }
      end
    end
  end

  def show
    redirect_to time_shifts_url
  end

  def new
    @time_shift = TimeShift.new default_time_shift_form
    render layout: 'static'
  end

  def edit
    @time_shift = TimeShift.find params[:id]
    authorize_action_for(@time_shift)
  end

  def create
    super do |success, _error|
      success.html do
        redirect_to new_time_shift_url,
                    flash: { notice: t('flash.time_shift_addition', hours: human_hours(@time_shift.hours), project: @time_shift.project,
                                                                    date: l(@time_shift.date)) }
      end
    end
  end

  def destroy
    @time_shift = TimeShift.find params[:id]
    authorize_action_for(@time_shift)
    @time_shift.destroy

    redirect_to time_shifts_url
  end

  private

  def build_summary
    SummaryQuery.for_user(
      current_user,
      period: params[:period] || 'week',
      group_by: params[:group_by]
    )
                .list_by_days
  end

  def default_time_shift_form
    selected_project = get_project_id_from_params
    {
      project_id: selected_project || current_user.time_shifts.order(:id).last.try(:project_id),
      date: Time.zone.today
    }
  end

  def get_project_id_from_params
    permitted_params
    return unless params[:time_shift][:project_id]

    project = Project.where(id: params[:time_shift][:project_id]).first
    project.id if current_user.membership_of(project)
  end

  def permitted_params
    # TODO: Check that the project is allowed to add time
    params[:time_shift] ||= {}
    params[:time_shift][:user_id] = current_user.id if action_name != 'update'
    params[:time_shift][:project_id] ||= nil
    params.require(:time_shift).permit!
    params
  end
end

app/views/time_shifts/_form.html.haml
= simple_form_for @time_shift, :html => { :class => 'time-shift-form', role: 'time_shift_form' } do |f|
  = f.error_notification
  .form-inputs
    .row
      .col-md-8.offset-md-3.col-sm-6.offset-sm-3
        .mb-3
          = f.label :date, class: 'form-label time-shift-form-label'
          .time-shift-form-input
            = f.input :date, :as => :date_picker, label: false, input_html: {class: 'form-control form-control-sm'}
        .mb-3
          = f.label :project, class: 'form-label time-shift-form-label'
          .time-shift-form-input
            = f.association :project, :include_blank => false, :collection => setable_projects_collection, label: false, input_html: {class: 'form-select form-select-sm'}
          -# = f.association :user, :include_blank => false, :collection => available_users_to_set_collection
        .mb-3
          = f.label :hours, class: 'form-label time-shift-form-label'
          .time-shift-form-input
            -# removed autofocus, because it hurts mobile experience
            = f.input :hours, as: :stepper, :input_html => {:min => 0.1, :max => 24, class: 'form-control form-control-sm' }, label: false
      .col-md-8.offset-md-3.col-sm-6.offset-sm-3
        .mb-3
          .time-shift-form-label
          .time-shift-form-input
            = f.input :description, :input_html => { :role => 'autosize', class: 'form-control form-control-sm' }, label: false
        .mb-3
          .time-shift-form-label
          .time-shift-form-button-submit
            .d-grid
              = button_tag type: 'submit', class: 'btn btn-primary btn-lg',
                :data => { 'disable-with' => t(:saving, :scope => [:simple_form, :button, :disable_with])} do
                = icon :ok, :white
                = t :create, :scope => [:helpers, :submit, :time_shift]
        .time-shift-form-label
        .time-shift-form-input
          .mb-3
            = f.button :button, :type=>:reset, :class => 'btn btn-link float-end' do
              Сбросить изменения
            .float-end
              - if @time_shift.present? && @time_shift.hours
                = TimeShiftDecorator.new(@time_shift).remove_link
            .clearfix

:coffee
  $form = $('@time_shift_form')
  $stepper_input = $form.find('@stepper input')
  App.reset_btn_hide $form, $form.find('button[type="reset"]')
  default_stepper_value = $stepper_input.val()
  $form.on 'reset', -> $stepper_input.attr 'value', default_stepper_value

app/views/time_shifts/_list.html.haml
- if time_shifts.present?
  %table.table.table-sm.table-striped.table-hover.time-shifts-table
    %thead
      %th.col-2
        = t 'time_shifts.date'
      %th.col-1= t 'time_shifts.time'
      %th.col-1= t 'time_shifts.project'
      %th.col-2= t 'time_shifts.collaborator'
      %th.col-5= t 'time_shifts.description'
      %th.print-hide.col-1
    - time_shifts.each do |ts|
      - ts = TimeShiftDecorator.decorate ts
      %tr{class: ts.tr_class}
        %td{ data: {'cell-title' => "#{t 'time_shifts.date'}" } }
          = ts.date
          -#%br
          -#%small.text-color-gray-light
            -#= ficon 'pencil-1'
            -#= l ts.updated_at

        %td{ data: {'cell-title' => "#{t 'time_shifts.date'}" } }
          %b= human_hours ts.hours
        %td{ data: {'cell-title' => "#{t 'time_shifts.project'}" } }
          = ts.project
        %td{ data: {'cell-title' => "#{t 'time_shifts.collaborator'}" } }
          = ts.user
        %td{ data: {'cell-title' => "#{t 'time_shifts.description'}" } }
          %small.text-muted= ts.description
        %td.print-hide
          .d-grid
            = ts.update_link :css_class =>'btn', :label => t('.edit')

- else
  .alert.alert-warning Нет результатов

app/views/time_shifts/_report.html.haml
- @result.result.each do |g|
  %h3.no-margin-top.pull-left
    = g[:title]
    %small
      = title_of_group_results g
  .pull-right
    - if @result.present?
      = render 'export_links'
  .clearfix
  = render 'list', :time_shifts => g[:time_shifts]

- if @result.result.present?
  = render 'print_ready'

app/views/time_shifts/_summary.html.haml
- if result[:columns].present?
  -#%div{ class: result.projects.count < 8 ? 'container' : '' }
  %table.table.summary-table
    %thead
      %tr
        %th
          Сводка за
          = summary_period_link result
          %br
          = summary_group_link result
        - result[:columns].each do |p|
          %th= p
        %th= t('time_shifts.total')

    %tbody
      - result[:days].each do |d|
        %tr
          %th{class: "#{week_day_class(d[:date])} summary-table-date"}= human_date d[:date]
          - result[:columns].each do |column|
            %td{class: week_day_class(d[:date]), data: {'cell-title' => column} }
              - if d[:columns][column.id].blank?
                .muted= '-'
              - else
                = summary_hours result, d, column
          %td{class: week_day_class(d[:date]), data: {'cell-title' => t('time_shifts.total')}}
            %b
              = link_to time_shifts_url(time_sheet_form: {date_from: d[:date], date_to: d[:date], group_by: :project}) do
                = human_hours result[:total_by_date][d[:date]]
      %tr{class:"summary-row"}
        %th
          За весь период:
        - result[:columns].each do |column|
          %td= human_hours result[:total_by_column][column.to_s]
        %td= human_hours result[:total]

  - if result[:columns].present?
    = render 'print_ready'

- else
  .container
    .alert.alert-info Нет сводных данных за ближайший период.

app/views/time_shifts/_time_sheet_form.html.haml
= simple_form_for @time_sheet_form, :url => time_shifts_url,
  :method => :get, :html => { :class => 'time-sheet-form form-horizontal' },:validate => true do |f|
  = f.error_notification
  = f.hidden_field :locale, :value => ""
  .form-inputs
    .row
      .col-md-4.col-md-offset-2.col-sm-4
        .form-group
          = f.label :date_from, class: 'col-sm-2'
          .col-sm-10
            = f.input :date_from,:as => :date_picker, :validate => true, label: false, input_html: {class: 'form-control input-sm'}
        .form-group
          = f.label :date_to, class: 'col-sm-2'
          .col-sm-10
            = f.input :date_to,:as => :date_picker, :validate => true, label: false, input_html: {class: 'form-control input-sm'}
      .col-md-2.col-md-offset-1.col-sm-4
        .form-group
          .col-xs-12
            = f.input :project_id, :collection => viewable_projects_collection, 
              :include_blank => t('simple_form.labels.project.any_project_id'), label: false, input_html: {class: 'form-control input-sm'}
        .form-group
          .col-xs-12
            = f.input :user_id, :collection => available_users_to_view_collection, 
              :include_blank => t('simple_form.labels.user.any_user_id'), label: false, input_html: {class: 'form-control input-sm'}

      -#.col-md-4
        .form-group
          = f.label :project_id, class: 'col-md-4'
          = f.input :project_id, :collection => viewable_projects_collection, :include_blank => 'Любой', label: false, input_html: {class: 'col-md-6'}
        .form-group
          = f.label :user_id, class: 'col-md-4'
          = f.input :user_id, :collection => available_users_to_view_collection, :include_blank => 'Любой', label: false, input_html: {class: 'col-md-6'}
      .col-md-2.col-md-offset-1.col-sm-4.time-sheet-group-by
        .col-xs-12
          = f.input :group_by, :collection => grouping_collection,  as: :radio_buttons, :item_wrapper_class => 'inline', label: false
    .form-actions
      .row
        .col-md-4.col-md-offset-2.col-sm-4
          .row
            .col-sm-10.col-sm-offset-2
              = button_tag type: 'submit', class: 'btn btn-primary btn-lg btn-block',
                :data => { 'disable-with' => t(:sending, :scope => [:simple_form, :button, :disable_with])} do
                = ficon :tasks, :white
                = t :create, :scope => [:helpers, :submit, :time_sheet_form]
        .col-md-6.col-sm-8
          = f.button :button, :type=>:reset, :class => 'btn btn-link pull-right' do
            %small.muted Сбросить фильтры
          .clearfix
%hr

:coffee
  $form = $('.time-sheet-form')
  App.reset_btn_hide $form, $form.find('button[type="reset"]')

app/views/time_shifts/blank.html.haml
= render 'time_sheet_form'

= render 'summary', result: result


-#%ul.horizontal
  -#%li= link_to 'Сводка', summary_time_shifts_url

app/views/time_shifts/edit.html.haml
.page-header
  %h1 Ой, я что-то напутал. Нужно отредактировать!

- if setable_projects_collection.empty?
  .alert.alert-warning У вас нет доступных проектов для тайминга.
- else
  = render 'form'

app/views/time_shifts/empty.html.haml
= render 'time_sheet_form'

.alert.alert-warning Выберите период, проект или исполнителя.

app/views/time_shifts/index.html.haml
.container
  = render 'time_sheet_form'

  - result.result.each do |g|
    %h3.no-margin-top
      = g[:title]
      %small
        = title_of_group_results g
    = render 'list', :time_shifts => g[:time_shifts]


  - if result.result.present?
    .pull-left
      = render 'print_ready'
    .pull-right
      - if result.present?
        = render 'export_links'
    .clearfix

app/views/time_shifts/new.html.haml
- if setable_projects_collection.empty?
  .print-hide.alert.alert-warning У вас нет доступных проектов для тайминга.
- else
  %br
  = render 'form'

- if this_day_shifts.exists?
  %br
  %h3= t '.today_shifts'
  = render 'list', :time_shifts => this_day_shifts

app/views/time_shifts/no_projects.html.haml
.alert.alert-warning
  У вас нет доступных проектов для тайминга.
  = link_to 'Заведите', new_project_url
  новый

app/views/time_shifts/summary.html.haml
-#.time-shifts-container
  .summary-table
= render 'summary', result: result